version: "3.7"

services:
  django:
    build:
      context: .
      dockerfile: dockerizing/app/Dockerfile
    image: crm_local_django
    volumes:
      - .:/usr/src/crm/
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - postgres

  postgres:
    image: postgres:11.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=lerolero
      - POSTGRES_DB=crm

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data:
    driver: local