version: "3.7"

services:
  django:
    build:
      context: .
      dockerfile: dockerizing/app/Dockerfile
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    # env_file: .env
    environment:
      - DEBUG=1
      - SECRET_KEY=c0#+t82qw5uefr0=1^_8#zq#ezw@-pf#5j8+foo)71-5of*dv-
      - POSTGRES_ENGINE=django.db.backends.postgresql
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=instatest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=lerolero
      - DATABASE=postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:11.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=lerolero
      - POSTGRES_DB=instatest

volumes:
  postgres_data:
    driver: local