# Generated by Django 3.0 on 2020-01-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='/media/profile_pics/no-img.jpg', upload_to='profile_pics/'),
        ),
    ]
