# Generated by Django 3.0 on 2020-01-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.CharField(default='profile_pics/no-img.jpg', max_length=255),
        ),
    ]
